/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Hero2268OverridesProps = {
    "19"?: PrimitiveOverrideProps<TextProps>;
    "22"?: PrimitiveOverrideProps<TextProps>;
    Hero2268?: PrimitiveOverrideProps<ViewProps>;
    "Group 1538"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 1439"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1437"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1436"?: PrimitiveOverrideProps<FlexProps>;
    "Group 1596"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 200"?: PrimitiveOverrideProps<ViewProps>;
    "Display Your Stories on any website, in seconds."?: PrimitiveOverrideProps<TextProps>;
    "Display Instagram Stories Widget on your website, that auto-syncs, and updates each time you add a photo in your active story."?: PrimitiveOverrideProps<TextProps>;
    "Frame 1"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1438"?: PrimitiveOverrideProps<FlexProps>;
    "form-control"?: PrimitiveOverrideProps<ViewProps>;
    "Enter your email..."?: PrimitiveOverrideProps<TextProps>;
    "btn-primary-lg3875742"?: PrimitiveOverrideProps<FlexProps>;
    "Start Free Trial3875743"?: PrimitiveOverrideProps<TextProps>;
    "arrow-right"?: PrimitiveOverrideProps<ViewProps>;
    Vector3875745?: PrimitiveOverrideProps<IconProps>;
    "Frame 1335"?: PrimitiveOverrideProps<FlexProps>;
    "Free 7-day trial"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 32"?: PrimitiveOverrideProps<IconProps>;
    "Easy setup"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 33"?: PrimitiveOverrideProps<IconProps>;
    "Cancel any time"?: PrimitiveOverrideProps<TextProps>;
    "Group 1537"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 1420"?: PrimitiveOverrideProps<FlexProps>;
    "popup-free"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 929"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1382"?: PrimitiveOverrideProps<FlexProps>;
    "Group 928"?: PrimitiveOverrideProps<FlexProps>;
    "Group 8843875758"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8783875759"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8693875760"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8673875761"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1403875762"?: PrimitiveOverrideProps<ImageProps>;
    "Group 883"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8693875764"?: PrimitiveOverrideProps<ViewProps>;
    "Group 868"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1403875766"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 142"?: PrimitiveOverrideProps<ViewProps>;
    "Group 914"?: PrimitiveOverrideProps<FlexProps>;
    escommerce?: PrimitiveOverrideProps<TextProps>;
    "Frame 1388"?: PrimitiveOverrideProps<FlexProps>;
    "1h ago"?: PrimitiveOverrideProps<TextProps>;
    "Line 46"?: PrimitiveOverrideProps<IconProps>;
    "Frame 1381"?: PrimitiveOverrideProps<FlexProps>;
    "Group 3353875774"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 283875775"?: PrimitiveOverrideProps<ViewProps>;
    "Group 313875776"?: PrimitiveOverrideProps<ViewProps>;
    Vector3875777?: PrimitiveOverrideProps<IconProps>;
    Vector3875778?: PrimitiveOverrideProps<IconProps>;
    Group?: PrimitiveOverrideProps<FlexProps>;
    "by EmbedSocial"?: PrimitiveOverrideProps<TextProps>;
    "Group 1418"?: PrimitiveOverrideProps<FlexProps>;
    "Group 1416"?: PrimitiveOverrideProps<ViewProps>;
    "Group 1396"?: PrimitiveOverrideProps<ViewProps>;
    "Group 866"?: PrimitiveOverrideProps<ViewProps>;
    KImage?: PrimitiveOverrideProps<ImageProps>;
    "Group 942"?: PrimitiveOverrideProps<ViewProps>;
    "Group 865"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 293875788"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 30"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 839"?: PrimitiveOverrideProps<FlexProps>;
    "Group 1403"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    sweaters?: PrimitiveOverrideProps<TextProps>;
    "Group 859"?: PrimitiveOverrideProps<FlexProps>;
    "Group 858"?: PrimitiveOverrideProps<ViewProps>;
    Sweaters?: PrimitiveOverrideProps<TextProps>;
    "1d ago"?: PrimitiveOverrideProps<TextProps>;
    "Group 1595"?: PrimitiveOverrideProps<ViewProps>;
    "Group 1498"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 2"?: PrimitiveOverrideProps<ImageProps>;
    "Group 9533875801"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 8423875802"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9523875803"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9383875804"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8983875805"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8843875806"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8783875807"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8693875808"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8673875809"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1403875810"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9513875811"?: PrimitiveOverrideProps<ViewProps>;
    Oct3875813?: PrimitiveOverrideProps<TextProps>;
    "Frame 8473875814"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9503875815"?: PrimitiveOverrideProps<ViewProps>;
    Vector3875816?: PrimitiveOverrideProps<IconProps>;
    Vector3875817?: PrimitiveOverrideProps<IconProps>;
    Vector3875818?: PrimitiveOverrideProps<IconProps>;
    "Frame 1419"?: PrimitiveOverrideProps<FlexProps>;
    "Group 34"?: PrimitiveOverrideProps<FlexProps>;
    "image 2"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 8423875822"?: PrimitiveOverrideProps<ViewProps>;
    "Group 1395"?: PrimitiveOverrideProps<ViewProps>;
    "Group 6833875824"?: PrimitiveOverrideProps<ViewProps>;
    "Group 143875825"?: PrimitiveOverrideProps<ViewProps>;
    "Pumpkin Spice"?: PrimitiveOverrideProps<TextProps>;
    "Group 8983875827"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8843875828"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8783875829"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8693875830"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8673875831"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1403875832"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 949"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4"?: PrimitiveOverrideProps<ImageProps>;
    "Group 9533875835"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 8423875836"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9523875837"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9383875838"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8983875839"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8843875840"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8783875841"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8693875842"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8673875843"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1403875844"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9513875845"?: PrimitiveOverrideProps<ViewProps>;
    Oct3875847?: PrimitiveOverrideProps<TextProps>;
    "Frame 8473875848"?: PrimitiveOverrideProps<ViewProps>;
    "Group 9503875849"?: PrimitiveOverrideProps<ViewProps>;
    Vector3875850?: PrimitiveOverrideProps<IconProps>;
    Vector3875851?: PrimitiveOverrideProps<IconProps>;
    Vector3875852?: PrimitiveOverrideProps<IconProps>;
    "Frame 8423875853"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8983875854"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8843875855"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8783875856"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8693875857"?: PrimitiveOverrideProps<ViewProps>;
    "Group 8673875858"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1403875859"?: PrimitiveOverrideProps<ImageProps>;
    "Group 6833875860"?: PrimitiveOverrideProps<ViewProps>;
    "Group 143875861"?: PrimitiveOverrideProps<ViewProps>;
    "Avocado Time"?: PrimitiveOverrideProps<TextProps>;
    "Group 1303"?: PrimitiveOverrideProps<ViewProps>;
    "Group 510"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 293875866"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 1560"?: PrimitiveOverrideProps<FlexProps>;
    "Group 336"?: PrimitiveOverrideProps<FlexProps>;
    embedsocial?: PrimitiveOverrideProps<TextProps>;
    "Group 3353875870"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 283875871"?: PrimitiveOverrideProps<ViewProps>;
    "Group 313875872"?: PrimitiveOverrideProps<ViewProps>;
    Vector3875873?: PrimitiveOverrideProps<IconProps>;
    Vector3875874?: PrimitiveOverrideProps<IconProps>;
    "Frame 49"?: PrimitiveOverrideProps<FlexProps>;
    "Group 43"?: PrimitiveOverrideProps<FlexProps>;
    "Home Stories Library3875877"?: PrimitiveOverrideProps<TextProps>;
    Arrow?: PrimitiveOverrideProps<IconProps>;
    "Home Stories Library3875879"?: PrimitiveOverrideProps<TextProps>;
    "Home Stories Library3875880"?: PrimitiveOverrideProps<TextProps>;
    "Get Started3875881"?: PrimitiveOverrideProps<TextProps>;
    "Group 1549"?: PrimitiveOverrideProps<FlexProps>;
    "Get Started3875883"?: PrimitiveOverrideProps<TextProps>;
    "btn-primary-lg3875884"?: PrimitiveOverrideProps<FlexProps>;
    "Start Free Trial3875885"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type Hero2268Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Hero2268OverridesProps | undefined | null;
}>;
export default function Hero2268(props: Hero2268Props): React.ReactElement;
